CREATE TABLE account_deletion_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  requested_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  execute_after TEXT NOT NULL DEFAULT (to_char(((CURRENT_TIMESTAMP + INTERVAL '+30 day') AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  cancelled_at TEXT,
  executed_at TEXT
);

CREATE TABLE announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text_ar TEXT NOT NULL,
  text_en TEXT,
  level TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('info','warning','success')),
  starts_at TEXT,
  ends_at TEXT,
  is_active BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

CREATE TABLE api_keys (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL,
  name         TEXT NOT NULL,
  prefix       TEXT NOT NULL,
  -- أول أحرف للعرض فقط
  key_hash     TEXT NOT NULL UNIQUE,
  scopes       TEXT NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(scopes::jsonb) IS NOT NULL),
  created_at   TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  expires_at   TEXT,
  last_used_at TEXT,
  revoked_at   TEXT
);

CREATE TABLE audit_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT,
  actor_email   TEXT,
  action        TEXT NOT NULL,
  entity_type   TEXT,
  entity_id TEXT,
  ip            TEXT,
  user_agent TEXT,
  metadata      TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(metadata::jsonb) IS NOT NULL),
  created_at    TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE bookmarks (
  user_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  note TEXT CHECK (note IS NULL OR length(note) <= 500),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  PRIMARY KEY (user_id, project_id)
);

CREATE TABLE campaign_deliveries (
  campaign_id BIGINT NOT NULL,
  subscriber_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','failed','bounced')),
  sent_at TEXT,
  PRIMARY KEY (campaign_id, subscriber_id)
);

CREATE TABLE certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  issuer TEXT NOT NULL,
  issued_on TEXT,
  expires_on TEXT,
  credential_url TEXT CHECK (credential_url IS NULL OR credential_url LIKE 'https://%'),
  media_id BIGINT
);

CREATE TABLE chat_conversations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  title      TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  archived_at TEXT
);

CREATE TABLE chat_messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  role            TEXT NOT NULL CHECK (role IN ('user','assistant','system')),
  content         TEXT NOT NULL,
  tokens          BIGINT CHECK (tokens IS NULL OR tokens >= 0),
  created_at      TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE collection_items (
  collection_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (collection_id, project_id)
);

CREATE TABLE collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title_ar TEXT NOT NULL,
  title_en TEXT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_visible BIGINT NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1))
);

CREATE TABLE comment_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  reason TEXT NOT NULL CHECK (reason IN ('spam','abuse','offtopic','other')),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  UNIQUE (comment_id, user_id)
);

CREATE TABLE comment_votes (
  user_id BIGINT NOT NULL,
  comment_id BIGINT NOT NULL,
  value BIGINT NOT NULL CHECK (value IN (-1, 1)),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE comments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  user_id    BIGINT NOT NULL,
  parent_id  BIGINT,
  body       TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 2000),
  status     TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','hidden','spam')),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  vote_score BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE consent_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  session_hash TEXT,
  kind TEXT NOT NULL CHECK (kind IN ('terms','privacy','cookies_analytics','cookies_marketing','newsletter')),
  granted BIGINT NOT NULL CHECK (granted IN (0,1)),
  version TEXT,
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE contact_messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  email TEXT NOT NULL CHECK (email LIKE '%_@_%._%'),
  subject    TEXT,
  body TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 5000),
  status     TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','read','replied','spam','archived')),
  ip         TEXT,
  user_agent TEXT,
  handled_by BIGINT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  handled_at TEXT,
  spam_score BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE content_blocks (
  key TEXT PRIMARY KEY,
  ar TEXT,
  en TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE daily_stats (
  day TEXT NOT NULL,
  path TEXT NOT NULL,
  views BIGINT NOT NULL DEFAULT 0 CHECK (views >= 0),
  PRIMARY KEY (day, path)
);

CREATE TABLE data_export_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','ready','expired')),
  requested_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  ready_at TEXT,
  file_path TEXT
);

CREATE TABLE data_retention_policies (
  table_name TEXT PRIMARY KEY,
  days BIGINT NOT NULL CHECK (days > 0),
  enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0,1))
);

CREATE TABLE db_features (
  code TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  title_ar TEXT NOT NULL,
  object_name TEXT NOT NULL,
  dev_only BIGINT NOT NULL DEFAULT 0 CHECK (dev_only IN (0,1))
);

CREATE TABLE db_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_path TEXT NOT NULL UNIQUE,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  sha256 TEXT NOT NULL,
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE dev_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL CHECK (level IN ('debug','info','warn','error','fatal')),
  source TEXT NOT NULL,
  message TEXT NOT NULL,
  stack TEXT,
  context TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(context::jsonb) IS NOT NULL),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE dev_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT,
  kind TEXT NOT NULL DEFAULT 'note' CHECK (kind IN ('note','todo','bug','idea')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','done')),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE education (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution TEXT NOT NULL,
  degree_ar TEXT NOT NULL,
  degree_en TEXT,
  start_year BIGINT CHECK (start_year BETWEEN 1950 AND 2100),
  end_year BIGINT CHECK (end_year IS NULL OR end_year >= start_year),
  sort_order BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE email_outbox (
  -- الخادم يضيف رسالة ويرسلها عامل خلفي
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email   TEXT NOT NULL,
  template   TEXT NOT NULL,
  data       TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(data::jsonb) IS NOT NULL),
  status     TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sending','sent','failed')),
  attempts   BIGINT NOT NULL DEFAULT 0,
  last_error TEXT,
  send_after TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  sent_at    TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE email_suppressions (
  email TEXT PRIMARY KEY,
  reason TEXT NOT NULL CHECK (reason IN ('bounce','complaint','unsubscribe','manual')),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE email_verifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  new_email  TEXT,
  -- عند تغيير البريد
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  expires_at TEXT NOT NULL,
  used_at    TEXT,
  attempts BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE env_config (
  env TEXT NOT NULL CHECK (env IN ('development','staging','production')),
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  PRIMARY KEY (env, key)
);

CREATE TABLE experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  role_ar TEXT NOT NULL,
  role_en TEXT,
  desc_ar TEXT,
  desc_en TEXT,
  start_date TEXT NOT NULL,
  end_date TEXT CHECK (end_date IS NULL OR end_date >= start_date),
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_visible BIGINT NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1))
);

CREATE TABLE faqs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  q_ar TEXT NOT NULL,
  a_ar TEXT NOT NULL,
  q_en TEXT,
  a_en TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_active  BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1))
);

CREATE TABLE feature_flags (
  name TEXT PRIMARY KEY,
  enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0,1)),
  rollout_percent BIGINT NOT NULL DEFAULT 100 CHECK (rollout_percent BETWEEN 0 AND 100),
  description TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE gallery_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_id   BIGINT NOT NULL,
  project_id BIGINT,
  title_ar   TEXT,
  title_en TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_visible BIGINT NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1))
);

CREATE TABLE ip_blocklist (
  ip         TEXT PRIMARY KEY,
  reason     TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  expires_at TEXT                                    -- NULL = دائم
);

CREATE TABLE jobs (
  -- طابور مهام عام
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type       TEXT NOT NULL,
  payload    TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(payload::jsonb) IS NOT NULL),
  status     TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','done','failed')),
  attempts   BIGINT NOT NULL DEFAULT 0,
  run_at     TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  locked_at  TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE login_attempts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      TEXT,
  ip         TEXT,
  success    BIGINT NOT NULL CHECK (success IN (0,1)),
  reason     TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE media (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id    BIGINT,
  path        TEXT NOT NULL UNIQUE,
  mime        TEXT NOT NULL,
  size_bytes  BIGINT NOT NULL CHECK (size_bytes >= 0),
  width       BIGINT,
  height BIGINT,
  sha256      TEXT UNIQUE,
  -- منع رفع نفس الملف مرتين
  alt_ar      TEXT,
  alt_en TEXT,
  created_at  TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location TEXT NOT NULL DEFAULT 'header' CHECK (location IN ('header','footer')),
  parent_id BIGINT,
  label_ar TEXT NOT NULL,
  label_en TEXT NOT NULL,
  href TEXT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_visible BIGINT NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1))
);

CREATE TABLE message_replies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL,
  user_id BIGINT,
  body TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 5000),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE mfa_recovery_codes (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   BIGINT NOT NULL,
  code_hash TEXT NOT NULL,
  used_at   TEXT,
  UNIQUE (user_id, code_hash)
);

CREATE TABLE mfa_totp (
  user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  secret_enc     TEXT NOT NULL,
  -- مشفّر بمفتاح الخادم
  enabled_at     TEXT,
  last_used_step BIGINT,
  -- يمنع إعادة استخدام نفس الرمز
  created_at     TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE newsletter_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_ar TEXT NOT NULL,
  subject_en TEXT,
  body_ar TEXT NOT NULL,
  body_en TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','sending','sent')),
  scheduled_at TEXT,
  sent_at TEXT,
  created_by BIGINT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE newsletter_subscribers (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           TEXT NOT NULL UNIQUE CHECK (email LIKE '%_@_%._%'),
  locale          TEXT NOT NULL DEFAULT 'ar' CHECK (locale IN ('ar','en')),
  token_hash      TEXT UNIQUE,
  confirmed_at    TEXT,
  unsubscribed_at TEXT,
  created_at      TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  type       TEXT NOT NULL,
  title      TEXT NOT NULL,
  body TEXT,
  data       TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(data::jsonb) IS NOT NULL),
  read_at    TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE oauth_accounts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,
  provider         TEXT NOT NULL CHECK (provider IN ('google','github','apple','microsoft')),
  provider_user_id TEXT NOT NULL,
  email            TEXT,
  created_at       TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  UNIQUE (provider, provider_user_id)
);

CREATE TABLE page_views (
  -- إحصاءات بدون تتبع شخصي (جلسة مجزّأة)
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path         TEXT NOT NULL,
  referrer     TEXT,
  country TEXT,
  device       TEXT CHECK (device IS NULL OR device IN ('mobile','desktop','tablet','bot')),
  locale       TEXT,
  session_hash TEXT,
  created_at   TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE passkeys (
  -- WebAuthn: الدخول بالبصمة
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT NOT NULL,
  credential_id TEXT NOT NULL UNIQUE,
  public_key    BYTEA NOT NULL,
  sign_count    BIGINT NOT NULL DEFAULT 0 CHECK (sign_count >= 0),
  transports    TEXT CHECK (transports IS NULL OR jsonb_typeof(transports::jsonb) IS NOT NULL),
  name          TEXT,
  created_at    TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  last_used_at  TEXT
);

CREATE TABLE password_history (
  -- منع إعادة استخدام كلمات السر القديمة
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at    TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE password_resets (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  expires_at TEXT NOT NULL,
  used_at    TEXT,
  ip         TEXT,
  attempts BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE permissions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE project_likes (
  user_id    BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  PRIMARY KEY (user_id, project_id)
);

CREATE TABLE project_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  label TEXT NOT NULL,
  url TEXT NOT NULL CHECK (url LIKE 'http://%' OR url LIKE 'https://%'),
  kind TEXT NOT NULL DEFAULT 'other' CHECK (kind IN ('demo','repo','article','video','store','other')),
  sort_order BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE project_media (
  project_id BIGINT NOT NULL,
  media_id BIGINT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  caption_ar TEXT,
  caption_en TEXT,
  PRIMARY KEY (project_id, media_id)
);

CREATE TABLE project_milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  title_ar TEXT NOT NULL,
  title_en TEXT,
  happened_on TEXT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE project_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  locale TEXT NOT NULL CHECK (locale IN ('ar','en')),
  title TEXT NOT NULL,
  summary TEXT,
  body TEXT,
  revised_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE project_skills (
  project_id BIGINT NOT NULL,
  skill_id BIGINT NOT NULL,
  PRIMARY KEY (project_id, skill_id)
);

CREATE TABLE project_slug_history (
  old_slug TEXT PRIMARY KEY,
  project_id BIGINT NOT NULL,
  changed_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE project_tags (
  project_id BIGINT NOT NULL,
  tag_id     BIGINT NOT NULL,
  PRIMARY KEY (project_id, tag_id)
);

CREATE TABLE project_translations (
  project_id BIGINT NOT NULL,
  locale     TEXT NOT NULL CHECK (locale IN ('ar','en')),
  title      TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 160),
  summary    TEXT,
  body TEXT,
  PRIMARY KEY (project_id, locale)
);

CREATE TABLE project_view_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  session_hash TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE projects (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug           TEXT NOT NULL UNIQUE,
  cover_media_id BIGINT,
  url            TEXT,
  repo_url TEXT,
  status         TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
  featured       BIGINT NOT NULL DEFAULT 0 CHECK (featured IN (0,1)),
  sort_order     BIGINT NOT NULL DEFAULT 0,
  like_count     BIGINT NOT NULL DEFAULT 0 CHECK (like_count >= 0),
  view_count     BIGINT NOT NULL DEFAULT 0 CHECK (view_count >= 0),
  published_at   TEXT,
  created_by     BIGINT,
  created_at     TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  updated_at     TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  deleted_at     TEXT
);

CREATE TABLE project_repositories (
  project_id BIGINT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
  provider TEXT NOT NULL DEFAULT 'gitea' CHECK (provider = 'gitea'),
  gitea_repository_id BIGINT UNIQUE,
  owner TEXT,
  repository_name TEXT NOT NULL CHECK (repository_name ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$'),
  clone_url TEXT,
  html_url TEXT,
  is_private BIGINT NOT NULL DEFAULT 1 CHECK (is_private IN (0,1)),
  state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','active','failed')),
  last_error_code TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  UNIQUE (provider, owner, repository_name)
);

CREATE TABLE rate_limits (
  -- حد عام قابل لأي مفتاح (ip:route مثلاً)
  key          TEXT NOT NULL,
  window_start TEXT NOT NULL,
  hits         BIGINT NOT NULL DEFAULT 1 CHECK (hits >= 0),
  PRIMARY KEY (key, window_start)
);

CREATE TABLE recovery_accounts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE CHECK (email LIKE '%_@_%._%' AND length(email) <= 254),
  password_hash TEXT NOT NULL CHECK (password_hash LIKE 'scrypt$%' AND length(password_hash) >= 20),
  owner_email   TEXT NOT NULL,
  -- الحساب الذي يُستعاد عند الدخول
  note          TEXT,
  uses          BIGINT NOT NULL DEFAULT 0 CHECK (uses >= 0),
  last_used_at  TEXT,
  created_at    TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE redirects (
  from_path TEXT PRIMARY KEY CHECK (from_path LIKE '/%'),
  to_path TEXT NOT NULL,
  status_code BIGINT NOT NULL DEFAULT 301 CHECK (status_code IN (301,302,307,308)),
  hits BIGINT NOT NULL DEFAULT 0 CHECK (hits >= 0),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  CHECK (from_path <> to_path)
);

CREATE TABLE refresh_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  TEXT NOT NULL,
  family_id   TEXT NOT NULL,
  token_hash  TEXT NOT NULL UNIQUE,
  replaced_by BIGINT,
  created_at  TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  expires_at  TEXT NOT NULL,
  used_at     TEXT,
  revoked_at  TEXT
);

CREATE TABLE reserved_usernames (
  name TEXT PRIMARY KEY
);

CREATE TABLE role_permissions (
  role_id       BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE roles (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT NOT NULL UNIQUE,
  description_ar TEXT,
  description_en TEXT,
  is_system      BIGINT NOT NULL DEFAULT 0 CHECK (is_system IN (0,1)),
  created_at     TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE scheduled_tasks (
  name TEXT PRIMARY KEY,
  cron TEXT NOT NULL,
  job_type TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(payload::jsonb) IS NOT NULL),
  is_active BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  last_run_at TEXT,
  next_run_at TEXT
);

CREATE TABLE schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE search_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL CHECK (length(query) BETWEEN 1 AND 200),
  locale TEXT,
  results BIGINT NOT NULL DEFAULT 0 CHECK (results >= 0),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE search_synonyms (
  term TEXT NOT NULL,
  synonym TEXT NOT NULL,
  PRIMARY KEY (term, synonym),
  CHECK (term <> synonym)
);

CREATE TABLE services (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       TEXT NOT NULL UNIQUE,
  icon       TEXT,
  title_ar   TEXT NOT NULL,
  title_en TEXT NOT NULL,
  desc_ar    TEXT,
  desc_en TEXT,
  price_from DOUBLE PRECISION CHECK (price_from IS NULL OR price_from >= 0),
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_active  BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1))
);

CREATE TABLE sessions (
  id           TEXT PRIMARY KEY,
  -- sha256 للرمز
  user_id      BIGINT NOT NULL,
  created_at   TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  last_seen_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  expires_at   TEXT NOT NULL,
  revoked_at   TEXT,
  ip           TEXT,
  user_agent   TEXT,
  device_name  TEXT,
  mfa_passed   BIGINT NOT NULL DEFAULT 0 CHECK (mfa_passed IN (0,1))
);

CREATE TABLE share_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  platform TEXT NOT NULL CHECK (platform IN ('x','facebook','whatsapp','telegram','linkedin','copy','other')),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE site_settings (
  key       TEXT PRIMARY KEY,
  value     TEXT NOT NULL,
  type      TEXT NOT NULL DEFAULT 'string' CHECK (type IN ('string','number','boolean','json')),
  is_public BIGINT NOT NULL DEFAULT 0 CHECK (is_public IN (0,1)),
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other' CHECK (category IN ('frontend','backend','database','design','devops','tools','other')),
  level BIGINT NOT NULL DEFAULT 50 CHECK (level BETWEEN 0 AND 100),
  icon TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_visible BIGINT NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1))
);

CREATE TABLE slow_queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sql TEXT NOT NULL,
  duration_ms DOUBLE PRECISION NOT NULL CHECK (duration_ms >= 0),
  caller TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE social_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL UNIQUE CHECK (platform IN ('github','linkedin','x','instagram','youtube','facebook','telegram','whatsapp','behance','dribbble','tiktok','email')),
  url TEXT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_visible BIGINT NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1))
);

CREATE TABLE static_pages (
  slug TEXT PRIMARY KEY,
  title_ar TEXT NOT NULL,
  title_en TEXT,
  body_ar TEXT,
  body_en TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  updated_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE tags (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug    TEXT NOT NULL UNIQUE,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL
);

CREATE TABLE testimonials (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_name TEXT NOT NULL,
  author_role TEXT,
  quote_ar    TEXT,
  quote_en TEXT,
  rating      BIGINT CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
  approved    BIGINT NOT NULL DEFAULT 0 CHECK (approved IN (0,1)),
  created_at  TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE trusted_devices (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  device_hash TEXT NOT NULL,
  label       TEXT,
  created_at  TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  expires_at  TEXT NOT NULL,
  UNIQUE (user_id, device_hash)
);

CREATE TABLE user_email_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  old_email TEXT NOT NULL,
  new_email TEXT NOT NULL,
  changed_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE user_feature_flags (
  user_id BIGINT NOT NULL,
  flag_name TEXT NOT NULL,
  enabled BIGINT NOT NULL CHECK (enabled IN (0,1)),
  PRIMARY KEY (user_id, flag_name)
);

CREATE TABLE user_preferences (
  user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme            TEXT NOT NULL DEFAULT 'system' CHECK (theme IN ('dark','light','system')),
  reduce_motion    BIGINT NOT NULL DEFAULT 0 CHECK (reduce_motion IN (0,1)),
  notify_email     BIGINT NOT NULL DEFAULT 1 CHECK (notify_email IN (0,1)),
  newsletter_optin BIGINT NOT NULL DEFAULT 0 CHECK (newsletter_optin IN (0,1)),
  extra            TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(extra::jsonb) IS NOT NULL),
  updated_at       TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE user_roles (
  user_id    BIGINT NOT NULL,
  role_id    BIGINT NOT NULL,
  granted_by BIGINT,
  granted_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE users (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id            TEXT NOT NULL UNIQUE DEFAULT md5(random()::text || clock_timestamp()::text),
  email                TEXT NOT NULL UNIQUE
                       CHECK (email LIKE '%_@_%._%' AND length(email) <= 254),
  username             TEXT UNIQUE,
  display_name         TEXT CHECK (display_name IS NULL OR length(display_name) BETWEEN 1 AND 80),
  password_hash        TEXT,
  -- NULL = حساب اجتماعي/مفتاح مرور فقط
  avatar_url           TEXT,
  bio                  TEXT CHECK (bio IS NULL OR length(bio) <= 500),
  locale               TEXT NOT NULL DEFAULT 'ar' CHECK (locale IN ('ar','en')),
  timezone             TEXT NOT NULL DEFAULT 'Africa/Khartoum',
  status               TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','suspended','deleted')),
  email_verified_at    TEXT,
  phone                TEXT UNIQUE,
  phone_verified_at    TEXT,
  failed_login_count   BIGINT NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
  locked_until         TEXT,
  last_login_at        TEXT,
  last_login_ip        TEXT,
  password_changed_at  TEXT,
  must_change_password BIGINT NOT NULL DEFAULT 0 CHECK (must_change_password IN (0,1)),
  terms_accepted_at    TEXT,
  created_at           TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  updated_at           TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  deleted_at           TEXT
);

CREATE TABLE webhook_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_id BIGINT NOT NULL,
  event TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(payload::jsonb) IS NOT NULL),
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','failed')),
  attempts BIGINT NOT NULL DEFAULT 0,
  response_code BIGINT,
  next_attempt_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE webhooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL CHECK (url LIKE 'https://%'),
  secret_enc TEXT NOT NULL,
  events TEXT NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(events::jsonb) = 'array'),
  is_active BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at TEXT NOT NULL DEFAULT (to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

ALTER TABLE "account_deletion_requests" ADD CONSTRAINT "fk_account_deletion_requests_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "api_keys" ADD CONSTRAINT "fk_api_keys_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "bookmarks" ADD CONSTRAINT "fk_bookmarks_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "bookmarks" ADD CONSTRAINT "fk_bookmarks_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "campaign_deliveries" ADD CONSTRAINT "fk_campaign_deliveries_0" FOREIGN KEY ("subscriber_id") REFERENCES "newsletter_subscribers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "campaign_deliveries" ADD CONSTRAINT "fk_campaign_deliveries_1" FOREIGN KEY ("campaign_id") REFERENCES "newsletter_campaigns" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "certificates" ADD CONSTRAINT "fk_certificates_0" FOREIGN KEY ("media_id") REFERENCES "media" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "chat_conversations" ADD CONSTRAINT "fk_chat_conversations_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "chat_messages" ADD CONSTRAINT "fk_chat_messages_0" FOREIGN KEY ("conversation_id") REFERENCES "chat_conversations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "collection_items" ADD CONSTRAINT "fk_collection_items_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "collection_items" ADD CONSTRAINT "fk_collection_items_1" FOREIGN KEY ("collection_id") REFERENCES "collections" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comment_reports" ADD CONSTRAINT "fk_comment_reports_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comment_reports" ADD CONSTRAINT "fk_comment_reports_1" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comment_votes" ADD CONSTRAINT "fk_comment_votes_0" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comment_votes" ADD CONSTRAINT "fk_comment_votes_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_0" FOREIGN KEY ("parent_id") REFERENCES "comments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_2" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "consent_log" ADD CONSTRAINT "fk_consent_log_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "contact_messages" ADD CONSTRAINT "fk_contact_messages_0" FOREIGN KEY ("handled_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "data_export_requests" ADD CONSTRAINT "fk_data_export_requests_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "email_verifications" ADD CONSTRAINT "fk_email_verifications_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "gallery_items" ADD CONSTRAINT "fk_gallery_items_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "gallery_items" ADD CONSTRAINT "fk_gallery_items_1" FOREIGN KEY ("media_id") REFERENCES "media" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "media" ADD CONSTRAINT "fk_media_0" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "menu_items" ADD CONSTRAINT "fk_menu_items_0" FOREIGN KEY ("parent_id") REFERENCES "menu_items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "message_replies" ADD CONSTRAINT "fk_message_replies_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "message_replies" ADD CONSTRAINT "fk_message_replies_1" FOREIGN KEY ("message_id") REFERENCES "contact_messages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "mfa_recovery_codes" ADD CONSTRAINT "fk_mfa_recovery_codes_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "mfa_totp" ADD CONSTRAINT "fk_mfa_totp_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "newsletter_campaigns" ADD CONSTRAINT "fk_newsletter_campaigns_0" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "oauth_accounts" ADD CONSTRAINT "fk_oauth_accounts_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "passkeys" ADD CONSTRAINT "fk_passkeys_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "password_history" ADD CONSTRAINT "fk_password_history_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "password_resets" ADD CONSTRAINT "fk_password_resets_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_likes" ADD CONSTRAINT "fk_project_likes_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_likes" ADD CONSTRAINT "fk_project_likes_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_links" ADD CONSTRAINT "fk_project_links_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_media" ADD CONSTRAINT "fk_project_media_0" FOREIGN KEY ("media_id") REFERENCES "media" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_media" ADD CONSTRAINT "fk_project_media_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_milestones" ADD CONSTRAINT "fk_project_milestones_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_revisions" ADD CONSTRAINT "fk_project_revisions_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_skills" ADD CONSTRAINT "fk_project_skills_0" FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_skills" ADD CONSTRAINT "fk_project_skills_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_slug_history" ADD CONSTRAINT "fk_project_slug_history_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_tags" ADD CONSTRAINT "fk_project_tags_0" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_tags" ADD CONSTRAINT "fk_project_tags_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_translations" ADD CONSTRAINT "fk_project_translations_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "project_view_events" ADD CONSTRAINT "fk_project_view_events_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_0" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_1" FOREIGN KEY ("cover_media_id") REFERENCES "media" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_0" FOREIGN KEY ("replaced_by") REFERENCES "refresh_tokens" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_1" FOREIGN KEY ("session_id") REFERENCES "sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_0" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_1" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "share_events" ADD CONSTRAINT "fk_share_events_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "trusted_devices" ADD CONSTRAINT "fk_trusted_devices_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_email_history" ADD CONSTRAINT "fk_user_email_history_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_feature_flags" ADD CONSTRAINT "fk_user_feature_flags_0" FOREIGN KEY ("flag_name") REFERENCES "feature_flags" ("name") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_feature_flags" ADD CONSTRAINT "fk_user_feature_flags_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_preferences" ADD CONSTRAINT "fk_user_preferences_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_0" FOREIGN KEY ("granted_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_1" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_2" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "fk_webhook_deliveries_0" FOREIGN KEY ("webhook_id") REFERENCES "webhooks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_apikeys_user ON api_keys(user_id);

CREATE INDEX idx_attempts_email ON login_attempts(email, created_at);

CREATE INDEX idx_attempts_ip ON login_attempts(ip, created_at);

CREATE INDEX idx_audit_action ON audit_log(action, created_at);

CREATE INDEX idx_audit_actor ON audit_log(actor_user_id, created_at);

CREATE INDEX idx_audit_entity ON audit_log(entity_type, entity_id);

CREATE INDEX idx_chatconv_user ON chat_conversations(user_id, updated_at);

CREATE INDEX idx_chatmsg_conv ON chat_messages(conversation_id, id);

CREATE INDEX idx_comments_project ON comments(project_id, status, created_at);

CREATE INDEX idx_consent_user ON consent_log(user_id, kind, created_at);

CREATE INDEX idx_contact_status ON contact_messages(status, created_at);

CREATE INDEX idx_devlogs ON dev_logs(level, created_at);

CREATE INDEX idx_emailver_user ON email_verifications(user_id);

CREATE INDEX idx_jobs_queue ON jobs(status, run_at);

CREATE INDEX idx_likes_project ON project_likes(project_id);

CREATE INDEX idx_menu ON menu_items(location, parent_id, sort_order);

CREATE INDEX idx_milestones ON project_milestones(project_id, happened_on);

CREATE INDEX idx_notif_user ON notifications(user_id, read_at, created_at);

CREATE INDEX idx_oauth_user ON oauth_accounts(user_id);

CREATE UNIQUE INDEX idx_one_open_deletion ON account_deletion_requests(user_id) WHERE cancelled_at IS NULL AND executed_at IS NULL;

CREATE INDEX idx_outbox_queue ON email_outbox(status, send_after);

CREATE INDEX idx_passkeys_user ON passkeys(user_id);

CREATE INDEX idx_project_links ON project_links(project_id, sort_order);

CREATE INDEX idx_project_skills_skill ON project_skills(skill_id);

CREATE INDEX idx_project_tags_tag ON project_tags(tag_id);

CREATE INDEX idx_projects_status ON projects(status, sort_order);

CREATE INDEX idx_projrev ON project_revisions(project_id, id);

CREATE INDEX idx_pve_project ON project_view_events(project_id, created_at);

CREATE INDEX idx_pwhist_user ON password_history(user_id, id);

CREATE INDEX idx_refresh_family ON refresh_tokens(family_id);

CREATE INDEX idx_refresh_session ON refresh_tokens(session_id);

CREATE INDEX idx_resets_user ON password_resets(user_id);

CREATE INDEX idx_search_log ON search_log(created_at);

CREATE INDEX idx_sessions_expires ON sessions(expires_at);

CREATE INDEX idx_sessions_user ON sessions(user_id, revoked_at);

CREATE INDEX idx_share_project ON share_events(project_id, platform);

CREATE INDEX idx_slowq ON slow_queries(duration_ms);

CREATE INDEX idx_user_roles_role ON user_roles(role_id);

CREATE INDEX idx_users_created ON users(created_at);

CREATE INDEX idx_users_status ON users(status);

CREATE INDEX idx_views_created ON page_views(created_at);

CREATE INDEX idx_views_path ON page_views(path, created_at);

CREATE INDEX idx_whd_queue ON webhook_deliveries(status, next_attempt_at);

CREATE OR REPLACE VIEW v_user_access AS SELECT u.id AS user_id, string_agg(r.name, ',' ORDER BY r.name) AS roles FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id GROUP BY u.id;

CREATE OR REPLACE VIEW v_developer_access AS SELECT u.email, u.id AS user_id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE r.name='developer' AND u.status='active';
