-- 011: سجل الميزات: كل ميزة مرتبطة بكائن فعلي في القاعدة (أو دالة في server/dev.ts) ويتحقق الاختبار منها
CREATE TABLE db_features (
  code TEXT PRIMARY KEY CHECK (code GLOB '[FD][0-9][0-9]' OR code = 'F100'),
  category TEXT NOT NULL, title_ar TEXT NOT NULL,
  object_name TEXT NOT NULL, dev_only INTEGER NOT NULL DEFAULT 0 CHECK (dev_only IN (0,1))
) STRICT, WITHOUT ROWID;
INSERT INTO db_features (code, category, title_ar, object_name, dev_only) VALUES
('F01','content','نسخ المشاريع عند كل تعديل','project_revisions',0),
('F02','content','الاحتفاظ بآخر 20 نسخة فقط','trg_project_revision_trim',0),
('F03','content','تاريخ الروابط القديمة للمشاريع','project_slug_history',0),
('F04','content','عرض تحويلات الروابط القديمة','v_slug_redirects',0),
('F05','content','أحداث مشاهدة المشروع وعدّاد تلقائي','project_view_events',0),
('F06','content','مجموعات المشاريع','collections',0),
('F07','content','عناصر المجموعات مع الترتيب','collection_items',0),
('F08','content','روابط إضافية للمشروع','project_links',0),
('F09','content','وسائط متعددة لكل مشروع','project_media',0),
('F10','content','الخط الزمني للمشروع','project_milestones',0),
('F11','content','المهارات','skills',0),
('F12','content','ربط المشاريع بالمهارات','project_skills',0),
('F13','content','الخبرات العملية','experience',0),
('F14','content','التعليم','education',0),
('F15','content','الشهادات','certificates',0),
('F16','content','روابط التواصل الاجتماعي','social_links',0),
('F17','content','صفحات ثابتة قابلة للتحرير','static_pages',0),
('F18','content','قوائم التنقل','menu_items',0),
('F19','content','تحويلات المسارات وعدّاد الزيارات','redirects',0),
('F20','content','شريط الإعلانات بفترة زمنية','announcements',0),
('F21','content','الإعلانات الفعّالة الآن','v_active_announcements',0),
('F22','content','كتل نصوص قابلة لإعادة الاستخدام','content_blocks',0),
('F23','search','بحث نصي كامل في الخدمات','services_fts',0),
('F24','search','بحث نصي كامل في الأسئلة الشائعة','faqs_fts',0),
('F25','search','سجل عمليات البحث','search_log',0),
('F26','search','مرادفات البحث','search_synonyms',0),
('F27','search','المشاريع الأكثر شعبية','v_popular_projects',0),
('F28','search','المشاريع المتشابهة بالوسوم','v_related_projects',0),
('F29','search','استخدام الوسوم','v_tag_usage',0),
('F30','search','المشروع كاملاً بالترجمتين والوسوم','v_project_full',0),
('F31','engagement','تصويت التعليقات ومجموع تلقائي','comment_votes',0),
('F32','engagement','بلاغات التعليقات','comment_reports',0),
('F33','engagement','إخفاء التعليق بعد 3 بلاغات','trg_comment_autohide',0),
('F34','engagement','حد عمق الردود','trg_comment_depth',0),
('F35','engagement','الرد من نفس المشروع فقط','trg_comment_same_project',0),
('F36','engagement','منع التعليقات عند إيقاف الميزة','trg_comments_enabled',0),
('F37','engagement','إشعار المديرين برسالة تواصل','trg_notify_contact',0),
('F38','engagement','إشعار المديرين بتعليق جديد','trg_notify_comment',0),
('F39','engagement','المفضلة','bookmarks',0),
('F40','engagement','أحداث المشاركة','share_events',0),
('F41','engagement','الشهادات المعتمدة للعرض العام','v_public_testimonials',0),
('F42','engagement','الخدمات الفعّالة للعرض العام','v_public_services',0),
('F43','engagement','الأسئلة الشائعة للعرض العام','v_public_faqs',0),
('F44','engagement','لوحة ما ينتظر المراجعة','v_pending_moderation',0),
('F45','engagement','الحملات البريدية','newsletter_campaigns',0),
('F46','engagement','تسليم الحملة لكل مشترك','campaign_deliveries',0),
('F47','engagement','كشف الرسائل المزعجة','trg_contact_spam',0),
('F48','engagement','حد معدل رسائل التواصل','trg_contact_rate',0),
('F49','engagement','ردود الرسائل وتحديث الحالة','message_replies',0),
('F50','engagement','وقت معالجة الرسالة تلقائياً','trg_contact_handled',0),
('F51','security','رفض كلمة سر غير مشفّرة','trg_pw_hashed_ins',0),
('F52','security','تاريخ تغيير البريد','user_email_history',0),
('F53','security','أسماء مستخدمين محجوزة','reserved_usernames',0),
('F54','security','تعبئة deleted_at تلقائياً','trg_user_deleted_at',0),
('F55','security','منع دخول حساب غير نشط','trg_login_active_only',0),
('F56','security','منع جلسة لحساب غير نشط','trg_session_active_only',0),
('F57','security','حد أقصى 10 جلسات نشطة','trg_session_cap',0),
('F58','security','كشف إعادة استخدام رمز التجديد','trg_refresh_reuse',0),
('F59','security','إنهاء الجلسة ينهي رموزها','trg_session_revoke_tokens',0),
('F60','security','حظر IP تلقائي بعد 20 فشل','trg_ip_autoblock',0),
('F61','security','رفض محاولات من IP محظور','trg_ip_blocked',0),
('F62','audit','تدقيق تفعيل المصادقة الثنائية','trg_audit_mfa',0),
('F63','audit','تدقيق مفاتيح API','trg_audit_apikey_new',0),
('F64','audit','تدقيق مفاتيح المرور','trg_audit_passkey_add',0),
('F65','audit','تدقيق ربط الحسابات الاجتماعية','trg_audit_oauth',0),
('F66','audit','تدقيق تغيير الإعدادات','trg_audit_settings',0),
('F67','audit','تدقيق حالة المشروع','trg_audit_project_status',0),
('F68','audit','تدقيق إشراف التعليقات','trg_audit_comment_status',0),
('F69','audit','تدقيق سحب الأدوار','trg_audit_role_revoked',0),
('F70','audit','تدقيق تغيير البريد','trg_audit_email',0),
('F71','audit','آخر 200 حدث تدقيق','v_audit_recent',0),
('F72','security','الدخول الفاشل آخر 24 ساعة','v_failed_logins_24h',0),
('F73','security','عناوين IP المشبوهة','v_suspicious_ips',0),
('F74','security','مفاتيح API القريبة من الانتهاء','v_expiring_api_keys',0),
('F75','security','مديرون بدون مصادقة ثنائية','v_admins_without_mfa',0),
('F76','security','جلسات قديمة بلا نشاط','v_stale_sessions',0),
('F77','analytics','نظرة صحة الموقع','v_site_health',0),
('F78','analytics','الزيارات حسب الدولة','v_traffic_by_country',0),
('F79','analytics','الزيارات حسب الجهاز','v_traffic_by_device',0),
('F80','analytics','أهم المصادر المُحيلة','v_top_referrers',0),
('F81','analytics','الزيارات بالساعة','v_hourly_views',0),
('F82','analytics','أكثر الصفحات زيارة 7 أيام','v_top_pages_7d',0),
('F83','analytics','الزيارات الشهرية','v_monthly_views',0),
('F84','analytics','تجميع يومي للزيارات','daily_stats',0),
('F85','analytics','تحديث التجميع تلقائياً','trg_daily_stats',0),
('F86','analytics','تجاهل زيارات الروبوتات','trg_views_ignore_bots',0),
('F87','analytics','فحص مسار الزيارة','trg_views_path',0),
('F88','privacy','سياسات الاحتفاظ بالبيانات','data_retention_policies',0),
('F89','privacy','طلبات تصدير البيانات','data_export_requests',0),
('F90','privacy','طلبات حذف الحساب بمهلة','account_deletion_requests',0),
('F91','privacy','سجل الموافقات','consent_log',0),
('F92','ops','أعلام الميزات','feature_flags',0),
('F93','ops','استثناءات الأعلام للمستخدم','user_feature_flags',0),
('F94','ops','الويب هوك','webhooks',0),
('F95','ops','تسليم الويب هوك','webhook_deliveries',0),
('F96','ops','ويب هوك عند نشر مشروع','trg_webhook_project_published',0),
('F97','ops','مهام مجدولة','scheduled_tasks',0),
('F98','ops','إعادة محاولة المهام الفاشلة','trg_job_retry',0),
('F99','ops','المهام العالقة','v_stuck_jobs',0),
('F100','ops','قائمة منع البريد','email_suppressions',0),
('D01','developer','دور المطور وصلاحيات dev.*','v_developer_access',1),
('D02','developer','سجل أخطاء المطور','dev_logs',1),
('D03','developer','سجل الاستعلامات البطيئة','slow_queries',1),
('D04','developer','ملاحظات ومهام المطور','dev_notes',1),
('D05','developer','سجل النسخ الاحتياطية','db_snapshots',1),
('D06','developer','إعدادات البيئات بدون أسرار','env_config',1),
('D07','developer','نظرة على بنية القاعدة','v_dev_schema',1),
('D08','developer','فحص سلامة القاعدة healthCheck','fn:healthCheck',1),
('D09','developer','مفتش القاعدة rowCounts/explain','fn:inspector',1),
('D10','developer','بيانات تجريبية seedDemo','fn:seedDemo',1);
